### ISSUE TITLE
all mirv_deathsmg commands don't work

### ISSUE THREAD

**Issue by huudiep1604** [advancedfx/advancedfx-prop#14]
Hi there, all mirv_deathsmg commands don't work in my HLAE software. All other commands work well. 
When I type mirv_deathsmg into console, the console still suggest some commands but they don't work when I use.
[Please] help me.
Or can someone help me by teamviewer please?
![untitled](https://cloud.githubusercontent.com/assets/20254973/16539949/1a73917c-407d-11e6-8f37-b2b862ffc8fc.png)

**Comment by dtugend** [comment]
Most likely your CS:GO client.DLL file has been modified in a way that HLAE is unable to work with.

This can have several reasons, it's always a good idea to have some Antivirus installed, for example https://www.avira.com is free (not saying it is good, but it's better than nothing, make sure to not install the other stuff it asks you when you install it, that's not required).

To fix the DLL please right click your game in the Steam Library, click Properties go to Local Files tab and select Verify Integrity Of Game Cache. Please let Steam finish the verification and also let it fix / redownload the missing / changed files. Then try again.

**Comment by dtugend** [comment]
Also please be aware that it will only display death messages in mirv_deathmsg debug, when they happen, meaning pausing the demo will cause nothing to be displayed in console.

**Comment by huudiep1604** [comment]
Thank you so much for your reply.
However, after I follow your steps all mirv_deathsmg commands still don't work. 
Could you please help me by teamviewer?

**Comment by dtugend** [comment]
Okay, add me in Steam:
https://steamcommunity.com/id/ripieces

**Comment by dtugend** [comment]
The problem was that con_filter_... was enabled in the config, filtering out console messages.
We changed con_filter_enabled to 0.
If your problem is fixed by that now, please close this issue :-)

**Comment by huudiep1604** [comment]
Thank you so much for your help. It works very well now. My problem is fixed.
