### ISSUE TITLE
__mirv_cstrike_ch_fps bug

### ISSUE THREAD

**Issue by CREEATION** [advancedfx/advancedfx-prop#2]
Hello,

by default, the `__mirv_cstrike_ch_fps`-fix is enabled.
When enabled (at least at 800x600 or lower resolutions), the crosshair gets "large", even when set to be "small".
Setting `__mirv_cstrike_ch_fps 0` removes the size problem and everything works fine again.
It also happens on my other demo I gave you from the issue before (https://github.com/ripieces/advancedfx/issues/1).

**Comment by dtugend** [comment]
Bug confirmed.

This bug doesn't affect recording with HLAE, it only affects preview when not recording (host_framerate 0).

**Comment by dtugend** [comment]
Fix will be pushed out with one of the next releases (not yet).
