### ISSUE TITLE
Failed to connect with local Steam Client process

### ISSUE THREAD

**Issue by CeleDKo** [advancedfx/advancedfx-prop#26]
Do not run the game through the program after an error "FATAL ERROR: Failed to connect with local Steam Client process" I was told to check the updated Steam. I checked, but I was told that the latest Steam versii..Ya restarted the program and Steam and nothing helped.

**Comment by dtugend** [comment]
**1) Make sure that Steam is running when launching CS:GO with HLAE**

**2) Make sure that neither Steam nor HLAE are launched with admin rights!**
How to check:
- right click Steam.exe in the Steam folder and go to compatibility tab and make sure that nothing is ticked there.
- do the same for HLAE.exe
  In case you changed s.th. don't forget to quit Steam and HLAE.exe and start them again.

**3) Make sure you are not launching an wrong old install of CS:GO:**
How to check:
Compare the path for CS:GO.exe in your HLAE settings with the one when you right click CS:GO in Steam Library select Properties from the Context menu and go to the LOCAL FILES tab and click BROWSE LOCAL FILES button (be sure to check the full path (usually starts with C:\ s.th.), not only the last folder).

**Comment by CeleDKo** [comment]
Thank you! Run Steam is not as Administrator solved the problem
