### ISSUE TITLE
Failed to Launch

### ISSUE THREAD

**Issue by JoelFardal** [advancedfx/advancedfx-prop#29]
I am getting a Failed to Launch error even though I followed an install tutorial exactly.

http://imgur.com/a/7cWDK

Those are the settings for Launch CSGO and Custom Loader and the error message I get with both.
The second image says Custom Loader Failed, but it's the same error.

**Comment by dtugend** [comment]
Most likely you have set csgo.exe to be run as administrator.

Please make sure that:
- You don't launch HLAE with admin rights and also not in compatibility mode, this is not required and will lead to problems.

**Also make sure that:**
- You don't launch CS:GO with admin rights and also not in compatibility mode, this is not required and will lead to problems.

In oder to do that, do this for each of HLAE.exe and csgo.exe in Explorer (in their respective folders, changing shortcuts won't help):
1) Right click -> Properties
2) Go to the compatibility tab
3) Make sure that "Execute/run program in compatibility mode" and "Execute/run program as administrator" are not checked (if they are checked then uncheck them)!
4) Click OK.

**Comment by ripieces** [comment]
Also make sure to change the settings for all users, there is a button "Change settings for all users." in the compatibility tab of the .exe properties dialogue.

**Comment by JoelFardal** [comment]
Worked perfectly. Thank you for the help.

https://www.youtube.com/watch?v=010iA37nIQc Here's the result.

**Comment by dtugend** [comment]
Glad it worked.
