### ISSUE TITLE
HIGHLIGHT

### ISSUE THREAD

**Issue by svetjana** [advancedfx/advancedfx-prop#33]
mirv_deathmsg highlightId X not highlighting anything, kills are coming without red outline

**Comment by svetjana** [comment]
in cs go

**Comment by dtugend** [comment]
How are you getting the value (id) for "X"?

The manual might help:
https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_deathmsg#controlling-highlighting

**Comment by dtugend** [comment]
Forget my previous message, CS:GO update broke it.

**Comment by svetjana** [comment]
mirv_deathmsg debug 1



Lähetetty Samsung Galaxy -älypuhelimesta.


-------- Alkuperäinen viesti --------
Lähettäjä: Dominik Tugend <notifications@github.com>
Päivämäärä: 4.2.2017 13.50 (GMT+02:00)
Saaja: ripieces/advancedfx <advancedfx@noreply.github.com>
Kopio: svetjana <mikko.piispanen@hotmail.com>, Author <author@noreply.github.com>
Aihe: Re: [ripieces/advancedfx] HIGHLIGHT (#33)


How are you getting the value (id) for "X"?

The manual might help:
https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_deathmsg#controlling-highlighting

**Comment by svetjana** [comment]
Aah ok :D i replied coz i didnt read this first



Lähetetty Samsung Galaxy -älypuhelimesta.


-------- Alkuperäinen viesti --------
Lähettäjä: Dominik Tugend <notifications@github.com>
Päivämäärä: 4.2.2017 14.04 (GMT+02:00)
Saaja: ripieces/advancedfx <advancedfx@noreply.github.com>
Kopio: svetjana <mikko.piispanen@hotmail.com>, Author <author@noreply.github.com>
Aihe: Re: [ripieces/advancedfx] HIGHLIGHT (#33)


Forget my previous message, CS:GO update broke it.

**Comment by BNEX** [comment]
yeah yeah, I looked that tutorials, but no one helps me, neither in the comments, have a lot of people was trying how to solve this problem as well.

but if someone finds here, they will find now ;)
