### ISSUE TITLE
Image and launch failed

### ISSUE THREAD

**Issue by Ahlster** [advancedfx/advancedfx-prop#35]
When i start CSGO it says "image failed" and "launch failed" csgo actually starts but i cant do the mirv comands, ive tryed all the hook things and i have tryed to redownload the program but nothing works, i searched on it and nothing helped. please help!

**Comment by dtugend** [comment]
The following programs are known to cause problems with HLAE:
- ChallangeMe.gg Anit Cheat client, [see this link](http://advancedfx.style-productions.net/forum/viewtopic.php?p=5848#p5848).
- Faceit Anti Cheat
- Comodo Cloud Anti-Virus

Please report back if that was your issue / if it was solved or not.

**Comment by Ahlster** [comment]
Yes, i have faceit anti cheat, but i dont wanna unistall faceit anti cheat, is there something i can do to use HLAE? The thing is, it started yesterday and worked just fine, but when i restarted my computer it didnt work again

**Comment by Ahlster** [comment]
ripieces, i logged out from faceit anti cheat and now its working! Thanks so much!

**Comment by dtugend** [comment]
Thanks for reporting back.
