### ISSUE TITLE
Can't launch csgo PLEASE HELP

### ISSUE THREAD

**Issue by Ahlster** [advancedfx/advancedfx-prop#39]
For the most of the time when I press launch it blinks and says ''some files has been moved... etc" ''do you wanna place them in the hlae_26_1.zip folder?'' I press no, nothing changes, I press yes, some files goes into the hlae folder, but nothing happens after that. But sometimes i manage to get into csgo and everything looks normal utill I watch a game. When im in the game i can't use console, use esc, change between players. I can't do anything. Please help!

**Comment by dtugend** [comment]
It's not possible to run HLAE from the .zip file, you need to extract (copy) **_all_ files and folders** in it into an empty folder you like and run HLAE.exe from there.

Edit: Please make sure to use the official download and not something else: https://github.com/ripieces/advancedfx/releases/latest

**Comment by dtugend** [comment]
Since you didn't reply back within 7 days I consider this solved.
If that's not the case, please leave a reply.
