### ISSUE TITLE
On HLAE when i try to run CSGO it comes up with 'FATAL ERROR:Failed to connect with local steam process!'

### ISSUE THREAD

**Issue by Lucas-Dove** [advancedfx/advancedfx-prop#40]
I've tried to restart steam, change folders and everything that i thought was necessary to help but obviously not enough.  

![image](https://cloud.githubusercontent.com/assets/27677882/25086492/f3fe7522-235f-11e7-8165-a4d71a1a440c.png)

**Comment by dtugend** [comment]
Please see https://github.com/ripieces/advancedfx/issues/26

**Comment by dtugend** [comment]
Since you didn't reply back within 7 days I consider this solved.
If that's not the case, please leave a reply.
