### ISSUE TITLE
IMAGE INJECTION FAILED, CUSTOMLOADER FAILED (cs:go)

### ISSUE THREAD

**Issue by StefanPeia** [advancedfx/advancedfx-prop#41]
I've put the correct hook.dll but when i try to launch from the custom launcher, it gives me those 2 errors: image injection failed and customloader failed. PLEASE HELP!

**Comment by dtugend** [comment]
This is a known issue with some other (i.e. Anti-Cheat) software, see https://github.com/ripieces/advancedfx/issues/35 for more information.

Edit or this FAQ entry: https://github.com/ripieces/advancedfx/wiki/FAQ#image-injection-failed--launch-failed

**Comment by dtugend** [comment]
Since you didn't reply back within 7 days I consider this solved.
If that's not the case, please leave a reply.
