### ISSUE TITLE
Starting to change parts to MIT license

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx-prop#42]
I want to put parts of advancedfx repository under the MIT license.
Thus I am starting to split advancedfx repository into modules.

@YaLTeR @nkoep @Snaacky - please tell me if you agree putting your contributions under the MIT license (you will be mentioned in the LINCENSE file of the modules that have source code you contributed to as Copyright holder, the year will be the one of your last contribution)

If you don't reply or say no, I will have to rewrite or remove code (I'd like to avoid that if possible).

**Comment by YaLTeR** [comment]
I agree with my contributions being relicensed under the MIT license.

**Comment by dtugend** [comment]
I also am asking Mirvin_Monkey btw, the original MDT (old name of HLAE) author back in 2007, but I didn't mention him above, since he doesn't have a GitHub account I know off.

Not sure what he will say though and if he will agree or not.

**Comment by dtugend** [comment]
Mirvin_Monkey told me by email he is fine with having his contributions under an MIT license (and him being mentioned as copyright holder), the only problem is that some of them are taken from some examples and only adjusted by him, so I need to take some care in regards to those code snippets.

**Comment by nkoep** [comment]
No objections from my side
