### ISSUE TITLE
Csgo dont start

### ISSUE THREAD

**Issue by lujplay** [advancedfx/advancedfx-prop#43]
Its always starting so i have blackscreen but the its kind of crashing cause the game doesnt start

**Comment by dtugend** [comment]
1) How long did you wait, it might take it a few seconds?

2) Check if you have any addons folder in your Counter-Strike Global Offensive\csgo directory, if so rename or delete it, it might contain outdated addons you installed earlier that cause problems now.

3) Verify your CS:GO installation: Right click CS:GO in Steam library and click "Properties", got to "LOCAL FILES" tab and select VERIFY GAME CACHE. This will take a few minutes, also it might need to re-download broken files!

**Comment by dtugend** [comment]
Since you didn't reply back within 7 days I consider this solved.
If that's not the case, please leave a reply.
