### ISSUE TITLE
CSGO WILL LAUNCH BUT AFTER MAP LOAD, IT CRASHES

### ISSUE THREAD

**Issue by svetjana** [advancedfx/advancedfx-prop#45]
Error - AfxHookSource
Problem in addresses.cpp:150
Problem in addresses.cpp:240
Problem in addresses.cpp:150
Problem in addresses.cpp:411
Problem in addresses.cpp:529
Problem in addresses.cpp:580
Problem in addresses.cpp:773
Problem in addresses.cpp:1173
Problem in addresses.cpp:1233
Problem in addresses.cpp:1667

**Comment by StolenArts** [comment]
I'm having the exact same problems.

**Comment by ediotr** [comment]
Me same problem, it happened after csgo update i think, please fix the problem asap!

**Comment by FDGOD13372** [comment]
Same problem here, is there anyway to fix it or do we have to wait for a updated HLAE?

**Comment by dztance** [comment]
Everyone will be experiencing this and unfortunately we just have to wait for the devs to fix :( 💯

**Comment by dztance** [comment]
Check https://twitter.com/dtugend?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor for devs twitter page he gives an ETA here

**Comment by ediotr** [comment]
he tweeted hlae will be updated after 30 mins and its been 30 mins already and still no update...

**Comment by dtugend** [comment]
How about now?

**Comment by dtugend** [comment]
Closing since you said you got it working here: https://github.com/advancedfx/advancedfx/issues/44#comment-381016101
