### ISSUE TITLE
Problems having with Launch.

### ISSUE THREAD

**Issue by ReVzPlays** [advancedfx/advancedfx-prop#47]
Either I'm missing something or i can't seem to do something right, and everything i do is wrong, So I'm watching youtube videos all are about the older updates but everytime i choose the source .dll for CS:GO its doesn't work, i do everything is should.. and everything everything else but it just doesn't work the game loads up with these errors keep popping up and i can't seem to avoid it at this point, I know you'll look at this and think Its simple and I'm stupid your right... I just need a little help thanks.

**Comment by dtugend** [comment]
Which errors? Can you give one example?
It's possible to accidentally select and an older install​ of AfxHoookSource.dll, since the browse dialogue tends to start in old folders.

To fix this either make sure that you change into the new folder, or use the File > Launch CS:GO dialogue instead

**Comment by dtugend** [comment]
Also make sure you have the latest HLAE version, 2.26.6 was just released a few hours ago and fixes problems with the CS:GO update​.

**Comment by forslund1** [comment]
Hello, I have the new version (2.26.6) and I have the same problems. These are the errors I'm getting:
System.ApplicationException: Failed to launch program, error code: 5 at AfxGui.loader(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment)

**Comment by dtugend** [comment]
Which antivirus are you using?
Are both injector.exe and x64\injector.exe present in HLAE.exe folder (you only need the former though for CS:GO)?

Edit: Some Anti Virus tend to remove those, by "behaviour" analysis. Please add an exception / update your AntiVirus.
I already reported the problem to AVG and they said they whitelisted those files.

**Comment by dtugend** [comment]
I edited my last comment above, please re-read it.
Also be sure to use HLAE 2.26.7, because there were some bugs that are fixed now (but are not related to the your problem).

**Comment by dtugend** [comment]
For some movie maker this was caused by Faceit Anticheat Client.

**Comment by x1mpl3** [comment]
Hello, I've got the version 2.26.7 and I got the problem that hlae won't even open,... I already looked for the anti virus, if the part I use is the right one and even if the "injector.exe" are in the folder (I hope it's ok to write my problem down here)

**Comment by dtugend** [comment]
@x1mpl3 I'd have preferred if you had opened an own issue (since it's not really related according to what you write), but it's too late now I guess :D

Which Operating System are you on?
You mean when you click HLAE.exe nothing happens?

Can you please check the Windows Application Event log for entries when you started HLAE.exe?
(On how to open it, please use a search engine and search for: _Windows \<Version here\> Application Event viewer_).

**Comment by x1mpl3** [comment]
I'm using windows 10 and I mean, when I click on hlae there comes the loading icon but that's it. There are also no entries in the Application Event Viewer after I tried opening hlae. I also tried earlier versions of hlae (2.26.6 giving me the same problems, 2.26.3 to 2.26.2 giving me errors "problem with addresses cpp:(number)" and with 2.26.1 to 2.26.0, hlae isn't even loaded, after I launch csgo with it)

**Comment by dtugend** [comment]
Wait we have a confusion then. So you can use the HLAE GUI to launch CS:GO, but after you launch CS:GO nothing happnes? Can you please take and post a screenshot of your Custom Loader settings, (though I always recommend to use File -> Launch CS:GO dialogue instead).

**Comment by x1mpl3** [comment]
No, I can't open the GUI with the latest version, just with earlier versions except 2.26.6... sorry for the Confusion ^^

**Comment by dtugend** [comment]
Oh okay, if possible please add me in Steam, so we can talk there: https://steamcommunity.com/id/ripieces

**Comment by dtugend** [comment]
The problem by @x1mpl3 is that due to an (old?) virus / trojan infection the window SmartScreen won't work and ask whether to allow executing HLAE.exe or not. We are working on fixing it, but it's not an HLAE problem and not related to the problem of the other people in this issue.

**Comment by dtugend** [comment]
Closing, because solved for x1mpl3 and lacking feedback from the other users (as said make sure you are not having FaceIT Anti Cheat running @forslund1 )

**Comment by Devalisk** [comment]
I'm using an external hard drive to download some steam games. You think this will affect it? I validated it and it said I was missing 1 file and it will be downloaded. I check again and it said all files are downloaded. Then DirectX starts downloading on steam. Still doesn't work after downloading all the necessary files. When I click on the .exe file multiple times, it says only one game can be run at one time.

**Comment by dtugend** [comment]
Yes, you might need to fix the permissions, so the user you launch HLAE / CS:GO from has access rights to the files.

Other option is to have all (Steam.exe, HLAE.exe and CS:GO.exe) set to be run as admin, but I don't recommend that, but it would work of course.
