### ISSUE TITLE
HLAE MOTION BLUR

### ISSUE THREAD

**Issue by svetjana** [advancedfx/advancedfx-prop#48]
I cant use motion blur in cs go when launched with HLAE.. This has been problem a while. I can enable it but i have to restart cs go after that.. (with hlae) and then if motion blur is enabled, i cant move my mouse cursor in demo. Can you fix this?

**Comment by dtugend** [comment]
1) HLAE does not tamper with motion_blur_enable unless you are using mirv_streams.
2) Motion blur should be able to be changed without restarting CS:GO, why do you have to restart it?
3) Motion blur should not change mouse cursor usage in demo. There is a bug though that can be triggered when spamming the home button in the menu.
4) What do you mean by "i cant move my mouse cursor in demo"?
5) Is your config / video.txt file in cfg folder write protected?
6) Are you using File -> Launch CS:GO and movie making config parent folder? (I'd recommend that.)

**Comment by svetjana** [comment]
What do you mean by "i cant move my mouse cursor in demo"?
I mean I see the cursor but i cant click anything with it.
its like this: http://forums.steampowered.com/forums/showthread.php?t=3097707
but thank you for the tips

**Comment by dtugend** [comment]
As said in 3. The Cursor is an UI bug (happens without HLAE too), that usually happens when you click spam certain elements of the UI (i.e. home button in Game Menu), please see if avoiding the spamming solves the issue for you (I know at least on guy that had this issue with the home button).

Also: Can you please check / answer the other questions?

**Comment by svetjana** [comment]
Yes I can.
1. Alright
2. I have to restart it (with hlae) that it applies it. There is no motion blur if I only turn it on. I have to always restart cs go. I have no problems with that cursor bug when I dont use hlae to launch cs go.
3. I havent pressed home button at all and the problem with cursor disappears always when motion blur in cs go is off.
5. It is write protected but if there is "mat_motion_blur_enabled  "1" , cursor bug strikes again.
6.I triedto use  "File -> Launch CS:GO and movie making config parent folder" but it didnt help me. 
There is videos in my youtube channel, recorded with motion blur, without HLAE
for example: https://www.youtube.com/watch?v=88ilTgdn60A
and when using hlae (cant use motion blur) the result is this:
https://www.youtube.com/watch?v=ynayHl4WnB4
Both videos are smooth but I prefer first one. I like it more because motion blur.
I can put motion blur afterwards with VirtualDub but it is not similar with first one.
My problem is minimal but annoying.
I can use motion blur only when not using HLAE. But I wanna those death notices with red outlines
And I do not want to put those afterwards. But It is Ok for me if no one can fix this. It is not apocalypse for me. 
But I really thank you for your support. :)

**Comment by svetjana** [comment]
and sorry my bad london

**Comment by dtugend** [comment]
Can you please provide me with your complete launch options in HLAE Custom Loader?
Also please provide me with the launch options you have set for CS:GO in Steam Library.

Asking because I want to try to reproduce the issue and so far failed all the time (I didn't try fullscreen yet though).

Edit: Btw if you can change it in HLAE, then it's not write protected, don't forget that the actual config is in Steam/userdata/<userid>/730/local/cfg folder by default nowadays.

**Comment by svetjana** [comment]
Can you please provide me with your complete launch options in HLAE Custom Loader?
-steam -insecure +sv_lan 1 -window -console -noborder -novid -w 1920 -h 1080 -game csgo 
Also please provide me with the launch options you have set for CS:GO in Steam Library.
-novid -console -full
I know that the file is there nowadays. I didnt change it when it was write protected (motion blur was 1 in config then) When it was 0, I kept it nonwrite protected, and changed it from the game.

**Comment by dtugend** [comment]
I still can't reproduce the problem.

If you are up for a [team viewer](https://www.teamviewer.com/) session, then add me in Steam:
http://steamcommunity.com/id/ripieces/

But I cannot guarantee that I'll find what's causing it and it could take a notable amount of time.

**Comment by svetjana** [comment]
Ok i will add you, and tomorrow I can contact you via team viewer. Maybe 16:00? The time is here 22.45 now

**Comment by svetjana** [comment]
The Problem solved, the problem was mat_postprocess_enable has to be 1
