### ISSUE TITLE
Mirv Commands Not working

### ISSUE THREAD

**Issue by Drag0nB0i** [advancedfx/advancedfx-prop#49]
I am trying to make a video and so i tried to do the command mirv_deathmsg debug 1 but it says unknown command every time! What do i do

**Comment by dtugend** [comment]
Please do not use custom loader and instead follow the text tutorial in the "Loading Counter-Strike Global Offensive" section here:
https://github.com/advancedfx/advancedfx/wiki/AfxHookSource#loading-counter-strike-global-offensive

If this doesn't solve your issue, please list any error message(s) you get when trying to launch from HLAE.

**Comment by dtugend** [comment]
Also use the correct repo next time for the issues please: https://github.com/advancedfx/advancedfx

**Comment by Drag0nB0i** [comment]
Its says there is a launching error but still launches and the mirv commands still dont work even though i did all the steps

![errororor](https://user-images.githubusercontent.com/38383961/38774182-74a226ae-4030-11e8-9025-906d2059c8a0.png)

**Comment by dtugend** [comment]
There's a hint in the error message:
It's not finding injector.exe.

**Please first make sure to extract _all_ files and folders from the ZIP file into a new empty folder and run HLAE.exe from there. HLAE.exe can not be run from the .zip file directly!**

That might already work. If it doesn't make sure that your Anti-Virus isn't deleting injector.exe in the HLAE.exe folder (add exception for injector.exe, re-download, re-extract).

**Comment by Drag0nB0i** [comment]
THANK YOU SO MUCH!!! XD it works
